bookie/bookie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('flightbook/', include("flightbook.urls")),
    path('', include('finance.urls')),
    path('admin/shell/', include('django_admin_shell.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', admin.site.urls),
]

bookie/finance/urls.py
from django.urls import path

from . import views

app_name = "finance"
urlpatterns = [
    path("", views.home, name="home"),
    path("overview/", views.overview, name="overview"),
    path("add-expense/", views.add_expense, name="addexpense"),
    path("add-income/", views.add_income, name="addincome"),
    path("category/<int:pk>/", views.CategoryDetail.as_view(), name="category-detail"),
]

bookie/flightbook/urls.py
from django.urls import path

from . import views

app_name = "flightbook"
urlpatterns = [
    path("add-flight/", views.add_flight, name="addflight"),
    path("add-commercial-flight/", views.add_commercial_flight, name="addcommercialflight"),
    path("flights/<str:pilot>/", views.FlightList.as_view(), name="flightlist"),
    path("commercial-day-summary/", views.commercial_day_summary, name="commercialdaysummary"),
    path("commercial-month-summary/", views.commercial_month_summary, name="commercialmonthsummary"),
    path("commercial-year-summary/", views.commercial_year_summary, name="commercialyearsummary"),
]

bookie/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load django_bootstrap5 %}

    {# Load Bootstrap CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# Load Bootstrap alerts #}
    {% bootstrap_messages %}
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'finance/style.css' %}">
    <link rel="stylesheet" href="{% static 'flightbook/style.css' %}">

    <title>Bookie Finanzen</title>


</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}

    {% endblock content %}
</body>
</html>

bookie/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">R&R's bookie</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Finanzen
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'finance:overview' %}">Übersicht</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'finance:addexpense' %}">Ausgabe erfassen</a></li>
              <li><a class="dropdown-item" href="{% url 'finance:addincome' %}">Einnahme erfassen</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Flugbuch
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'flightbook:flightlist' 'Rafael' %}">Flugbuch Rafael</a></li>
              <li><a class="dropdown-item" href="{% url 'flightbook:flightlist' 'Roli' %}">Flugbuch Roli</a></li>
              <li><a class="dropdown-item" href="{% url 'flightbook:commercialdaysummary' %}">Tageszusammenfassung</a></li>
              <li><a class="dropdown-item" href="{% url 'flightbook:commercialmonthsummary' %}">Monatszusammenfassung</a></li>
              <li><a class="dropdown-item" href="{% url 'flightbook:commercialyearsummary' %}">Jahreszusammenfassung</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'flightbook:addflight' %}">Flug erfassen</a></li>
              <li><a class="dropdown-item" href="{% url 'flightbook:addcommercialflight' %}">Kommerziellen Flug erfassen</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>