bookie/bookie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('flightbook/', include("flightbook.urls")),
    path('', include('finance.urls')),
    path('admin/shell/', include('django_admin_shell.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', admin.site.urls),
]

bookie/finance/urls.py
from django.urls import path

from . import views

app_name = "finance"
urlpatterns = [
    path("", views.home, name="home"),
    path("overview/", views.overview, name="overview"),
    path("add-expense/", views.add_expense, name="addexpense"),
    path("add-income/", views.add_income, name="addincome"),
    path("category/<int:pk>/", views.CategoryDetail.as_view(), name="category-detail"),
]

bookie/flightbook/urls.py
from django.urls import path

from . import views

app_name = "flightbook"
urlpatterns = [
    path("add-flight/", views.add_flight, name="addflight"),
    path("add-commercial-flight/", views.add_commercial_flight, name="addcommercialflight"),
    path("flights/<str:pilot>/", views.FlightList.as_view(), name="flightlist"),
    path("commercial-day-summary/", views.commercial_day_summary, name="commercialdaysummary"),
    path("commercial-month-summary/", views.commercial_month_summary, name="commercialmonthsummary"),
    path("commercial-year-summary/", views.commercial_year_summary, name="commercialyearsummary"),
]

bookie/finance/models.py
from django.db import models
from django.contrib import admin


class Category(models.Model):
    name = models.CharField(max_length=64)
    monthly_budget = models.FloatField(default=0)
    saldo = models.FloatField(default=0)

    class Meta:
        verbose_name = "Kategorie"
        verbose_name_plural = "Kategorien"

    def __str__(self):
        return self.name

    def calculate_saldo(self):
        self.saldo = sum([income.amount for income in self.income_set.all()])\
            - sum([expense.amount for expense in self.expense_set.all()])
        self.save()


class Expense(models.Model):
    name = models.CharField(max_length=128)
    amount = models.FloatField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date = models.DateField()

    class Meta:
        verbose_name = "Ausgabe"
        verbose_name_plural = "Ausgaben"

    def __str__(self):
        return self.name


class Income(models.Model):
    name = models.CharField(max_length=128)
    amount = models.FloatField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date = models.DateField()

    class Meta:
        verbose_name = "Einnahme"
        verbose_name_plural = "Einnahmen"

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=128)
    saldo = models.FloatField(default=0)

    class Meta:
        verbose_name = "Konto"
        verbose_name_plural = "Konten"

    def __str__(self):
        return self.name

bookie/finance/forms.py
from django import forms

from .models import Expense, Income


class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = [
            'name',
            'amount',
            'category',
            'date',
        ]
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = [
            'name',
            'amount',
            'category',
            'date',
        ]
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

bookie/finance/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
import datetime
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import ExpenseForm, IncomeForm

from .models import Category, Account


@login_required
def home(request):
    return render(request, "finance/home.html")


@login_required    
def overview(request):
    template_name = "finance/overview.html"

    total_categories = sum([category.saldo for category in Category.objects.all()])
    total_accounts = sum([account.saldo for account in Account.objects.all()])

    difference = total_accounts - total_categories

    context = {
        "categories": Category.objects.all(),
        "accounts": Account.objects.all(),
        "difference": difference,
    }
    return render(request, template_name, context)

@login_required
def add_expense(request):
    if request.method == "POST":
        form = ExpenseForm(request.POST)
        if form.is_valid():
            form.save()
            for category in Category.objects.all():
                category.calculate_saldo()
                category.save()
            return HttpResponseRedirect(reverse("finance:home"))
    else:
        initial = {"date": timezone.now().strftime("%Y-%m-%d")}
        if Category.objects.filter(name="Haushalt").exists():
            initial["category"] = Category.objects.get(name="Haushalt")
        form = ExpenseForm(initial=initial)

    return render(request, "finance/add_expense.html", {"form": form})

@login_required
def add_income(request):
    if request.method == "POST":
        form = IncomeForm(request.POST)
        if form.is_valid():
            form.save()
            for category in Category.objects.all():
                category.calculate_saldo()
                category.save()
            return HttpResponseRedirect(reverse("finance:home"))
    else:
        initial = {"date": timezone.now().strftime("%Y-%m-%d")}
        form = IncomeForm(initial=initial)

    return render(request, "finance/add_income.html", {"form": form})


class CategoryDetail(LoginRequiredMixin, generic.DetailView):
    model = Category
    template_name = "finance/category.html"

    def get_context_data(self, **kwargs):
        show_last = 10
        context = super().get_context_data(**kwargs)
        context["expenses"] = self.object.expense_set.order_by("-date")[:show_last]
        context["incomes"] = self.object.income_set.order_by("-date")[:show_last]
        return context

bookie/templates/finance/add_expense.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container">
    <h4>Ausgabe erfassen</h4>
    <hr>
    <form action="{% url 'finance:addexpense' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
        <a class="btn btn-primary" href="{% url 'finance:overview' %}">Zurück</a>
        <button type="submit" class="btn btn-primary">Speichern</button>
    </form>
</div>
{% endblock %}

bookie/templates/finance/add_income.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container">
    <h4>Einnahme erfassen</h4>
    <hr>
    <form action="{% url 'finance:addincome' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
        <a class="btn btn-primary" href="{% url 'finance:overview' %}">Zurück</a>
        <button type="submit" class="btn btn-primary">Speichern</button>

    </form>
</div>
{% endblock %}

bookie/templates/finance/category.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h3>Details {{ category.name }}</h3>

    <p>Saldo: {{ category.saldo|floatformat:2 }} CHF</p>
    <h4>Ausgaben</h4>
    {% if expenses %}
        <table class="table">
            <thead>
                <tr>
                    <th>Datum</th>
                    <th>Bezeichnung</th>
                    <th>Betrag (CHF)</th>
                </tr>
            </thead>
            <tbody>
            {% for expense in expenses %}
                <tr>
                    <td>{{ expense.date }}</td>
                    <td>{{ expense.name }}</td>
                    <td>{{ expense.amount|floatformat:2 }} </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Keine Ausgaben</p>
    {% endif %}
    <hr>
    <h4>Einnahmen</h4>
    {% if incomes %}
        <table class="table">
            <tr>
                <th>Datum</th>
                <th>Bezeichnung</th>
                <th>Betrag (CHF)</th>
            </tr>
            {% for income in incomes %}
                <tr>
                    <td>{{ income.date }}</td>
                    <td>{{ income.name }}</td>
                    <td>{{ income.amount|floatformat:2 }} </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>Keine Einnahmen</p>
    {% endif %}
</div>
{% endblock content %}

bookie/templates/finance/home.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
<link rel="stylesheet" href="{% static 'finance/style.css' %}">

{% block content %}
<div class="container">
    <p>Willkommen, ich bin Bookie! Wie kann ich behilflich sein?</p>
    <hr>
    <h4>Finanzen</h4>
    <a class="btn btn-primary" href="{% url 'finance:addexpense' %}">Ausgabe erfassen</a>
    <a class="btn btn-primary" href="{% url 'finance:addincome' %}">Einnahme erfassen</a>
    <hr>
    <h4>Flugbuch</h4>
    <a class="btn btn-primary" href="{% url 'flightbook:addflight' %}">Flug erfassen</a>
    <a class="btn btn-primary" href="{% url 'flightbook:addcommercialflight' %}">Kommerziellen Flug erfassen</a>


</div>
{% endblock %}

bookie/templates/finance/overview.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h4>Kategorien</h4>
        {% if categories %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Saldo</th>
                        <th>Monatliches Budget</th>
                    </tr>
                </thead>
                <tbody>
                {% for category in categories %}
                    <tr>
                        <td><a href="{% url 'finance:category-detail' category.id %}">{{ category.name }}</a></td>
                        <td>{{ category.saldo|floatformat:2 }} CHF</td>
                        <td>{{ category.monthly_budget|floatformat:2 }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>Keine Kategorien</p>
        {% endif %}

        <h4>Konten</h4>
        {% if accounts %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Saldo</th>
                    </tr>
                </thead>
                <tbody>
                {% for account in accounts %}
                    <tr>
                        <td>{{ account.name }}</td>
                        <td>{{ account.saldo|floatformat:2 }} CHF</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>Keine Konten</p>
        {% endif %}
        
        <b>
            <p>Differenz: {{ difference|floatformat:2 }} CHF</p>
        </b>
        
    </div>

{% endblock content %}